bump_version: null
lint: null
nf_core_version: 3.0.0
org_path: null
repository_type: pipeline
template:
  author: Nico Trummer
  description: A single cell transcriptomics pipeline for QC, integration and making
    the results presentable
  force: false
  is_nfcore: true
  name: scdownstream
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
