contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #scdownstream channel"
    url: https://nfcore.slack.com/channels/scdownstream
    about: Discussion about the nf-core/scdownstream pipeline
